export default {
  'love_propensity': [
    'is always in love with somebody and easily develops positive feelings',
    'very easily falls into love and develops positive feelings',
    'can easily fall in love or develop positive sentiments',
    'does not easily fall in love and rarely develops positive sentiments',
    'is not the type to fall in love or even develop positive feelings',
    'never falls in love or develops positive feelings toward anything',
  ],
  'hate_propensity': [
    'is often inflamed by hatred and easily develops hatred toward things',
    'is prone to hatreds and often develops negative feelings',
    'is quick to form negative views about things',
    'does not easily hate or develop negative feelings',
    'very rarely develops negative feelings toward things',
    'never feels hatred toward anyone or anything',
  ],
  'envy_propensity': [
    'is consumed by overpowering feelings of jealousy',
    'is prone to strong feelings of jealousy',
    'often feels envious of others',
    'doesn\'t often feel envious of others',
    'is rarely jealous',
    'never envies others their status, situation or possessions',
  ],
  'cheer_propensity': [
    'often feels filled with joy',
    'can be very happy and optimistic',
    'is often cheerful',
    'is rarely happy or enthusiastic',
    'is dour as a rule',
    'is never the slightest bit cheerful about anything',
  ],
  'depression_propensity': [
    'is frequently depressed',
    'is often sad and dejected',
    'often feels discouraged',
    'rarely feels discouraged',
    'almost never feels discouraged',
    'never feels discouraged',
  ],
  'anger_propensity': [
    'is in a constant state of internal rage',
    'is very quick to anger',
    'is quick to anger',
    'is slow to anger',
    'is very slow to anger',
    'never becomes angry',
  ],
  'anxiety_propensity': [
    'is a nervous wreck',
    'is always tense and jittery',
    'is often nervous',
    'has a calm demeanor',
    'has a very calm demeanor',
    'has an incredibly calm demeanor',
  ],
  'lust_propensity': [
    'is constantly ablaze with feelings of lust',
    'is prone to strong feelings of lust',
    'often feels lustful',
    'does not often feel lustful',
    'rarely looks on others with lust',
    'never feels lustful passions',
  ],
  'stress_vulnerability': [
    'becomes completely helpless in stressful situations',
    'cracks easily under pressure',
    'doesn\'t handle stress well',
    'can handle stress',
    'is confident under pressure',
    'is impervious to the effects of stress',
  ],
  'greed': [
    'is as avaricious as they come, obsessed with acquiring wealth',
    'is very greedy',
    'has a greedy streak',
    'doesn\'t focus on material goods',
    'desires little for herself in the way of possessions',
    'often neglects her own wellbeing, having no interest in material goods',
  ],
  'immoderation': [
    'is ruled by irresistible cravings and urges',
    'feels strong urges and seeks short-term rewards',
    'occasionally overindulges',
    'doesn\'t often experience strong cravings or urges',
    'only rarely feels strong cravings or urges',
    'never feels tempted to overindulge in anything',
  ],
  'violent': [
    'is given to rough-and-tumble brawling, even to the point of starting fights for no reason',
    'would never pass up a chance for a good fistfight',
    'likes to brawl',
    'tends to avoid any physical confrontations',
    'does not enjoy participating in physical confrontations',
    'would flee even the most necessary battle to avoid any form of physical confrontation',
  ],
  'perseverance': [
    'is unbelievably stubborn, and will stick with even the most futile action once her mind is made up',
    'is very stubborn',
    'is stubborn',
    'has a noticeable lack of perseverance',
    'doesn\'t stick with things if even minor difficulties arise',
    'drops any activity at the slightest hint of difficulty or even the suggestion of effort being required',
  ],
  'wastefulness': [
    'is completely careless with resources when completing projects, and invariably wastes a lot of time and effort',
    'is not careful with resources when working on projects and often spends unnecessary effort',
    'tends to be a little wasteful when working on projects',
    'tends to be a little tight with resources when working on projects',
    'is stingy with resources on projects and refuses to expend any extra effort',
    'cuts any corners possible when working on a project, regardless of the consequences, rather than wasting effort or resources',
  ],
  'discord': [
    'revels in chaos and discord, and she encourages it whenever possible',
    'finds a chaotic mess preferable to the boredom of harmonious living',
    'doesn\'t mind a little tumult and discord in day-to-day living',
    'prefers that everyone live as harmoniously as possible',
    'feels best when everyone gets along without any strife or contention',
    'would be deeply satisfied if everyone could live as one in complete harmony',
  ],
  'friendliness': [
    'is quite a bold flatterer, extremely friendly but just a little insufferable',
    'is very friendly and always tries to say nice things to others',
    'is a friendly individual',
    'is somewhat quarrelsome',
    'is unfriendly and disagreeable',
    'is a dyed-in-the-wool quarreler, never missing a chance to lash out in verbal hostility',
  ],
  'politeness': [
    'exhibits a refined politeness and is determined to keep the guiding rules of etiquette and decorum as if life itself depended on it',
    'is very polite and observes appropriate rules of decorum when possible',
    'is quite polite',
    'could be considered rude',
    'is very impolite and inconsiderate of propriety',
    'is a vulgar being who does not care a lick for even the most basic rules of civilized living',
  ],
  'disdain_advice': [
    'disdains even the best advice of associates and family, relying strictly on her own counsel',
    'dislikes receiving advice, preferring to keep her own counsel',
    'has a tendency to go it alone, without considering the advice of others',
    'tends to ask others for help with difficult decisions',
    'relies on the advice of others during decision making',
    'is unable to make decisions without a great deal of input from others',
  ],
  'bravery': [
    'is utterly fearless when confronted with danger, to the point of lacking common sense',
    'is incredibly brave in the face of looming danger, perhaps a bit foolhardy',
    'is brave in the face of imminent danger',
    'is somewhat fearful in the face of imminent danger',
    'has great trouble mastering fear when confronted by danger',
    'is a coward, completely overwhelmed by fear when confronted with danger',
  ],
  'confidence': [
    'presupposes success in any venture requiring her skills with what could be called blind overconfidence',
    'is extremely confident of herself in situations requiring her skills',
    'is generally quite confident of her abilities when undertaking specific ventures',
    'sometimes acts with little determination and confidence',
    'lacks confidence in her abilities',
    'has no confidence at all in her talent and abilities',
  ],
  'vanity': [
    'is completely wrapped up in her own appearance, abilities and other personal matters',
    'is greatly pleased by her own looks and accomplishments',
    'is pleased by her own appearance and talents',
    'is not inherently proud of her talents and accomplishments',
    'takes no pleasure in her talents and appearance',
    'could not care less about her appearance, talents or other personal vanities',
  ],
  'ambition': [
    'has a relentless drive, completely consumed by ambition',
    'is very ambitious, always looking for a way to better her situation',
    'is quite ambitious',
    'isn\'t particularly ambitious',
    'is not driven and rarely feels the need to pursue even a modest success',
    'has no ambition whatsoever',
  ],
  'gratitude': [
    'unerringly returns favors and has a profound sense of gratitude for the kind actions of others',
    'feels a strong need to reciprocate any favor done for her',
    'is grateful when others help her out and tries to return favors',
    'takes offered help and gifts without feeling particularly grateful',
    'accepts favors without developing a sense of obligation, preferring to act as the current situation demands',
    'does not feel the slightest need to reciprocate favors that others do for her, no matter how major the help or how much she needed it',
  ],
  'immodesty': [
    'always presents herself as extravagantly as possible, displaying a magnificent image to the world',
    'likes to present herself boldly, even if it would offend an average sense of modesty',
    'doesn\'t mind wearing something special now and again',
    'prefers to present herself modestly',
    'presents herself modestly and frowns on any flashy accoutrements',
    'cleaves to an austere lifestyle, disdaining even minor immodesties in appearance',
  ],
  'humor': [
    'finds something humorous in everything, no matter how serious or inappropriate',
    'finds the humor in most situations',
    'has an active sense of humor',
    'has little interest in joking around',
    'does not find most jokes humorous',
    'is utterly humorless',
  ],
  'vengeful': [
    'is vengeful and never forgets or forgives past grievances',
    'has little time for forgiveness and will generally seek retribution',
    'tends to hang on to grievances',
    'doesn\'t tend to hold on to grievances',
    'does not generally seek retribution for past wrongs',
    'has no sense of vengeance or retribution',
  ],
  'pride': [
    'is absorbed in delusions of self-importance',
    'has an overinflated sense of self-worth',
    'thinks she is fairly important in the grand scheme of things',
    'is very humble',
    'has a low sense of self-esteem',
    'is completely convinced of her own worthlessness',
  ],
  'cruelty': [
    'is deliberately cruel to those unfortunate enough to be subject to her sadism',
    'is sometimes cruel',
    'generally acts impartially and is rarely moved to mercy',
    'often acts with compassion',
    'is easily moved to mercy',
    'always acts with mercy and compassion at the forefront of her considerations',
  ],
  'singleminded': [
    'pursues matters with a single-minded focus, often overlooking other matters',
    'can be very single-minded',
    'generally acts with a narrow focus on the current activity',
    'can occasionally lose focus on the matter at hand',
    'is somewhat scatterbrained',
    'is a complete scatterbrain, unable to focus on a single matter for more than a passing moment',
  ],
  'hopeful': [
    'has such a developed sense of optimism that she always assumes the best outcome will eventually occur, no matter what',
    'is an optimist',
    'generally finds herself quite hopeful about the future',
    'tends to assume the worst of two outcomes will be the one that comes to pass',
    'is a pessimist',
    'despairs of anything positive happening in the future and lives without feelings of hope',
  ],
  'curious': [
    'is implacably curious, without any respect for propriety or privacy',
    'is very curious, sometimes to her detriment',
    'is curious and eager to learn',
    'isn\'t particularly curious about the world',
    'is very rarely moved by curiosity',
    'is incurious and never seeks out knowledge or information to satisfy herself',
  ],
  'bashful': [
    'is gripped by a crippling shyness',
    'is bashful',
    'tends to consider what others think of her',
    'is not particularly interested in what others think of her',
    'is generally unhindered by the thoughts of others concerning her actions',
    'is shameless, absolutely unfazed by the thoughts of others',
  ],
  'privacy': [
    'is private to the point of paranoia, unwilling to reveal even basic information about herself',
    'has a strong tendency toward privacy',
    'tends not to reveal personal information',
    'tends to share her own experiences and thoughts with others ',
    'is not a private person and freely shares details of her life',
    'shares intimate details of life without sparing a thought to repercussions or propriety',
  ],
  'perfectionist': [
    'is obsessed with details and will often take a great deal of extra time to make sure things are done the right way',
    'is a perfectionist',
    'tries to do things correctly each time',
    'doesn\'t try to get things done perfectly',
    'is inattentive to detail in her own work',
    'is frustratingly sloppy and careless with every task she sets to carry out',
  ],
  'closeminded': [
    'is completely closed-minded and never changes her mind after forming an initial idea',
    'is intellectually stubborn, rarely changing her mind during a debate regardless of the merits',
    'tends to be a bit stubborn in changing her mind about things',
    'doesn\'t cling tightly to ideas and is open to changing her mind',
    'often finds herself changing her mind to agree with somebody else',
    'easily changes her mind and will generally go with the prevailing view on anything',
  ],
  'tolerant': [
    'is not bothered in the slightest by deviations from the norm or even extreme differences in lifestyle or appearance',
    'is very comfortable around others that are different from her',
    'is quite comfortable with others that have a different appearance or culture',
    'is somewhat uncomfortable around those that appear unusual or live differently from her',
    'is made deeply uncomfortable by differences in culture or appearance',
    'cannot tolerate differences in culture, lifestyle or appearance',
  ],
  'emotionally_obsessive': [
    'is emotionally obsessive, forming life-long attachments even if they aren\'t reciprocated',
    'forms strong emotional bonds with others, at times to her detriment',
    'has a tendency toward forming deep emotional bonds with others',
    'tends to form only tenuous emotional bonds with others',
    'forms only fleeting and rare emotional bonds with others',
    'does not have feelings of emotional attachment and has never felt even a moment\'s connection with another being',
  ],
  'swayed_by_emotions': [
    'is buffeted by others\' emotions and can\'t help but to respond to them',
    'is swayed by emotional appeals',
    'tends to be swayed by the emotions of others',
    'tends not to be swayed by emotional appeals',
    'does not generally respond to emotional appeals',
    'is never moved by the emotions of others',
  ],
  'altruism': [
    'is truly fulfilled by assisting those in need',
    'finds helping others very emotionally rewarding',
    'finds helping others emotionally rewarding',
    'does not go out of her way to help others',
    'dislikes helping others',
    'feels helping others is an imposition on her time',
  ],
  'dutifulness': [
    'has a profound sense of duty and obligation',
    'has a strong sense of duty',
    'has a sense of duty',
    'finds obligations confining',
    'dislikes obligations and will try to avoid being bound by them',
    'hates vows, obligations, promises and other binding elements that could restrict her',
  ],
  'thoughtlessness': [
    'never deliberates before acting, to the point of being considered thoughtless',
    'doesn\'t generally think before acting',
    'can sometimes act without deliberation',
    'tends to think before acting',
    'can get caught up in internal deliberations when action is necessary',
    'never acts without prolonged deliberation, even to her own detriment and the harm of those around her',
  ],
  'orderliness': [
    'is obsessed with order and structure in her own life, with everything kept in its proper place',
    'lives an orderly life, organized and neat',
    'tries to keep her things orderly',
    'tends to make a small mess with her own possessions',
    'is sloppy with her living space',
    'is completely oblivious to any conception of neatness and will just leave things strewn about without a care',
  ],
  'trust': [
    'is naturally trustful of everybody',
    'is very trusting',
    'is trusting',
    'is slow to trust others',
    'does not trust others',
    'sees others as selfish and conniving',
  ],
  'gregariousness': [
    'truly treasures the company of others',
    'enjoys being in crowds',
    'enjoys the company of others',
    'tends to avoid crowds',
    'prefers to be alone',
    'considers spending time alone much more important than associating with others',
  ],
  'assertiveness': [
    'is assertive to the point of aggression, unwilling to let others get a word in edgewise when she has something to say',
    'has an overbearing personality',
    'is assertive',
    'tends to be passive in discussions',
    'only rarely tries to assert herself in conversation',
    'would never under any circumstances speak up or otherwise put forth her point of view in a discussion',
  ],
  'activity_level': [
    'is driven by a bouncing frenetic energy',
    'lives at a high-energy kinetic pace',
    'lives a fast-paced life',
    'likes to take it easy',
    'lives at a slow-going and leisurely pace',
    'has an utterly languid pace of easy living, calm and slow',
  ],
  'excitement_seeking': [
    'never fails to seek out the most stressful and even dangerous situations',
    'seeks out exciting and adventurous situations',
    'likes a little excitement now and then',
    'doesn\'t seek out excitement',
    'actively avoids exciting or stressful situations',
    'does everything in her power to avoid excitement and stress',
  ],
  'imagination': [
    'is bored by reality and would rather disappear utterly and forever into a world of made-up fantasy',
    'is given to flights of fancy to the point of distraction',
    'has an active imagination',
    'isn\'t given to flights of fancy',
    'is grounded in reality',
    'is interested only in facts and the real world',
  ],
  'abstract_inclined': [
    'eschews practical concerns for philosophical discussion, puzzles, riddles and the world of ideas',
    'strongly prefers discussions of ideas and abstract concepts over handling specific practical issues',
    'has a tendency to consider ideas and abstractions over practical applications',
    'likes to keep things practical, without delving too deeply into the abstract',
    'dislikes abstract discussions and would much rather focus on practical examples',
    'is concerned only with matters practical to the situation at hand, with absolutely no inclination toward abstract discussion',
  ],
  'art_inclined': [
    'can easily become absorbed in art and the beauty of the natural world',
    'greatly moved by art and natural beauty',
    'is moved by art and natural beauty',
    'does not have a great aesthetic sensitivity',
    'is not readily moved by art or natural beauty',
    'is completely unmoved by art or the beauty of nature',
  ],
};
