export default {
  'analytical_ability': [
    'awesome intellectual powers',
    'great analytical abilities',
    'a sharp intellect',
    'a good intellect',
    '(no description)',
    'poor analytical abilities',
    'very bad analytical abilities',
    'a lousy intellect',
    'a stunning lack of analytical ability',
  ],
  
  'focus': [
    'unbreakable focus',
    'a great ability to focus',
    'very good focus',
    'the ability to focus',
    '(no description)',
    'poor focus',
    'quite poor focus',
    'really poor focus',
    'the absolute inability to focus',
  ],
  
  'willpower': [
    'an unbreakable will',
    'an iron will',
    'a lot of willpower',
    'willpower',
    '(no description)',
    'little willpower',
    'a large deficit of willpower',
    'next to no willpower',
    'absolutely no willpower',
  ],
  
  'creativity': [
    'a boundless creative imagination',
    'great creativity',
    'very good creativity',
    'good creativity',
    '(no description)',
    'meager creativity',
    'poor creativity',
    'lousy creativity',
    'next to no creative talent',
  ],
  
  'intuition': [
    'uncanny intuition',
    'great intuition',
    'very good intuition',
    'good intuition',
    '(no description)',
    'bad intuition',
    'very bad intuition',
    'lousy intuition',
    'horrible intuition',
  ],
  
  'patience': [
    'absolutely boundless patience',
    'a deep well of patience',
    'a great deal of patience',
    'a sum of patience',
    '(no description)',
    'a shortage of patience',
    'little patience',
    'very little patience',
    'no patience at all',
  ],
  
  
  'memory': [
    'an astonishing memory',
    'an amazing memory',
    'a great memory',
    'a good memory',
    '(no description)',
    'an iffy memory',
    'a poor memory',
    'a really bad memory',
    'little memory to speak of',
  ],
  
  'linguistic_ability': [
    'an astonishing ability with languages and words',
    'a great affinity for language',
    'a natural inclination toward language',
    'a way with words',
    '(no description)',
    'a little difficulty with words',
    'little linguistic ability',
    'very little linguistic ability',
    'difficulty with words and language',
  ],
  
  'spatial_sense': [
    'a stunning feel for spatial relationships',
    'an amazing spatial sense',
    'a great feel for the surrounding space',
    'a good spatial sense',
    '(no description)',
    'a questionable spatial sense',
    'poor spatial senses',
    'an atrocious spatial sense',
    'no sense for spatial relationships',
  ],
  
  'musicality': [
    'an astonishing knack for music',
    'a great musical sense',
    'a natural ability with music',
    'a feel for music',
    '(no description)',
    'an iffy sense for music',
    'little natural inclination toward music',
    'next to no natural musical ability',
    'absolutely no feel for music at all',
  ],
  
  'kinestetic_sense': [
    'an astounding feel for the position of her own body',
    'a great kinesthetic sense',
    'a very good sense of the position of her own body',
    'a good kinesthetic sense',
    '(no description)',
    'a meager kinesthetic sense',
    'a poor kinesthetic sense',
    'a very clumsy kinesthetic sense',
    'an unbelievably atrocious sense of the position of her own body',
  ],
  
  'empathy': [
    'an absolutely remarkable sense of others\' emotions',
    'a great sense of empathy',
    'a very good sense of empathy',
    'an ability to read emotions fairly well',
    '(no description)',
    'poor empathy',
    'a very bad sense of empathy',
    'next to no empathy',
    'the utter inability to judge others\' emotions',
  ],
  
  'social_awareness': [
    'a shockingly profound feel for social relationships',
    'a great feel for social relationships',
    'a very good feel for social relationships',
    'a good feel for social relationships',
    '(no description)',
    'a meager ability with social relationships',
    'a poor ability to manage or understand social relationships',
    'a lack of understanding of social relationships',
    'an absolute inability to understand social relationships',
  ],
};
